server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            clientId: api-client
            clientSecret: secret
            authorizationGrantType: authorization_code
            redirectUri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            clientName: api-client-oidc
          api-client-authorization-code:
            provider: spring
            clientId: api-client
            clientSecret: secret
            authorizationGrantType: authorization_code
            redirectUri: " http://127.0.0.1:8080/authorized"
            scope: api.read
            clientName: api-client-authorization-code
        provider:
          spring:
            issuer-uri: http://localhost:9000




