server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/db
    username: sa
    password:
    driverClassName: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            clientId: api-client
            clientSecret: secret
            authorizationGrantType: authorization_code
            redirectUri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            clientName: api-client-oidc
          api-client-authorization-code:
            provider: spring
            clientId: api-client
            clientSecret: secret
            authorizationGrantType: authorization_code
            redirectUri: " http://127.0.0.1:8080/authorized"
            scope: api.read
            clientName: api-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000

